import = ["/home/carlos/.config/alacritty/themes/catppuccin_mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "MesloLGS NF"

#[font.bold]
#family = "UbuntuMono Nerd Font"
#style = "Regular"
#
#[font.italic]
#family = "UbuntuMono Nerd Font"
#style = "Regular"
#
#[font.normal]
#family = "UbuntuMono Nerd Font"
#style = "Regular"
